/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import "./globals.css";
import NaveBary from "@/components/navgat/NaveBary";
import 'bootstrap/dist/css/bootstrap.min.css';
import ReduxProvider from "./reduxProvider";
import Footer from "@/components/Footer";
import 'bootstrap/dist/css/bootstrap.min.css';
export const metadata: Metadata = {
  title: "Next.js App redux",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Geist&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="font-sans antialiased text-[#333] ]"
      >
        <ReduxProvider>
          <NaveBary />
          {children}
          <Footer />
        </ReduxProvider>

      </body>
    </html>


  );
}
